import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:a/widgets/button.dart' as button;

// Generated by: https://www.figma.com/community/plugin/842128343887142055/

class WelcomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final screenWidth = constraints.maxWidth;
        final screenHeight = constraints.maxHeight;
        double relWidth(double w) => screenWidth * (w / 440);
        double relHeight(double h) => screenHeight * (h / 956);

        return Column(
          children: [
            Container(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              clipBehavior: Clip.antiAlias,
              decoration: BoxDecoration(color: const Color(0xFF355E3B)),
              child: Stack(
                children: [
                  Positioned(
                    bottom: 0,
                    left: 0,
                    right: 0,
                    child: SvgPicture.asset(
                      'assets/bolas.svg',
                      fit: BoxFit.cover,
                    ),
                  ),
                  Positioned(
                    left: relWidth(60),
                    top: relHeight(109),
                    child: Container(
                      width: relWidth(321),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Center(
                            child: SvgPicture.asset(
                              'assets/logo.svg',
                              width: relWidth(140), // ajusta según necesites
                              height: relWidth(140),
                            ),
                          ),
                          FittedBox(
                            fit: BoxFit.scaleDown,
                            child: Row(
                              children: [
                                Text(
                                  'EcologicPoint',
                                  style: GoogleFonts.agbalumo(
                                    color: const Color(0xFFA8C686),
                                    fontSize: relWidth(48),
                                    fontWeight: FontWeight.w700,
                                    decoration: TextDecoration.none,
                                  ),
                                ),
                                Text(
                                  '+',
                                  style: GoogleFonts.agbalumo(
                                    color: const Color(0xFFA8C686),
                                    fontSize: relWidth(48),
                                    fontWeight: FontWeight.w700,
                                    decoration: TextDecoration.none,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: relHeight(597),
                    child: Container(
                      width: screenWidth,
                      padding: EdgeInsets.only(
                        left: relWidth(24),
                        right: relWidth(24),
                        bottom: relHeight(48),
                      ),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: relHeight(72),
                        children: [
                          Container(
                            width: double.infinity,
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              spacing: relHeight(24),
                              children: [
                                SizedBox(
                                  width: relWidth(392),
                                  child: Text(
                                    '¡Bienvenido!',
                                    textAlign: TextAlign.center,
                                    style: GoogleFonts.agbalumo(
                                      color: const Color(0xFF355E3B),
                                      fontSize: 40,
                                      fontWeight: FontWeight.w400,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                                SizedBox(
                                  width: relWidth(392),
                                  child: Text(
                                    'Tu experiencia comienza aquí.\n Explora, descubre y disfruta.',
                                    textAlign: TextAlign.center,
                                    style: GoogleFonts.poppins(
                                      color: const Color(0xFF1F1F1F),
                                      fontSize: relWidth(16),
                                      fontWeight: FontWeight.w400,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Container(
                            width: double.infinity,
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              spacing: relHeight(12),
                              children: [
                                Container(
                                  width: double.infinity,
                                  padding: EdgeInsets.symmetric(
                                    horizontal: relWidth(16),
                                    vertical: relHeight(8),
                                  ),

                                  child: button.FilledButton(
                                    isActivated: true,
                                    text: 'Iniciar sesión',
                                    onPressed: () {
                                      Navigator.pushNamed(context, '/login');
                                    },
                                  ),
                                ),
                                Container(
                                  width: double.infinity,
                                  padding: EdgeInsets.symmetric(
                                    horizontal: relWidth(16),
                                    vertical: relHeight(8),
                                  ),
                                  child: button.CustomOutlinedButton(
                                    text: 'Crear cuenta',
                                    isActivated: true,
                                    onPressed: () {
                                      // Navigator.pushNamed(context, '/register');
                                    },
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: 0,
                    child: Container(
                      width: screenWidth,
                      height: relHeight(51),
                      clipBehavior: Clip.antiAlias,
                      decoration: BoxDecoration(),
                      child: Stack(
                        children: [
                          Positioned(
                            left: relWidth(35),
                            top: relHeight(12),
                            child: Container(
                              width: relWidth(54),
                              height: relHeight(21),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(24),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        );
      },
    );
  }
}
